RGO 2017
tue-robotics/nl_robot_console pull request #11
Opened 2017-05-09 18:41 UTC by MatthijsBurgh

2017-05-10 07:39 UTC, LoyVanBeek requested changes

2017-05-10 07:39 UTC, LoyVanBeek commented on src/nl_robot_console/console.py
> +        self.cl_wm = rospy.ServiceProxy(robot_name + "/ed/simple_query", SimpleQuery)
I guess this means "client for the world model" but please a clearer variable name

2017-05-20 16:40 UTC, rokusottervanger approved these changes

2017-05-20 16:40 UTC, LoyVanBeek approved these changes

2017-05-20 16:41 UTC, merged